project:
  type: book
  resources:
    - notebooks/*.qmd

lang: zh

book:
  title: "R语言学习笔记"
  author: "一把Fei刀"
  date: 2023/2/5
  search: true
  page-navigation: true
  favicon: images/favicon.png
  chapters:
    - index.qmd
    - part: tidymodels
      chapters:
        - chapters/tidymodels-基础.qmd
        - chapters/tidymodels-进阶.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
    comments:
      hypothesis: true
    toc: true
    toc_float: true
    number-sections: true
    lightbox: true
    code-fold: show
    code-overflow: wrap
    code-link: true
    code-tools: true

crossref:
  chapters: true

execute:
  freeze: auto
  tidy: true
  echo: true
  message: false
  warning: false


