project:
  type: book

lang: zh

book:
  title: "R语言学习笔记"
  author: "一把Fei刀"
  date: 2023/2/5
  search: true
  favicon: images/favicon.png
  chapters:
    - index.qmd
    - chapters/tidymodels.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
    comments:
      hypothesis: true
    toc: true
    toc_float: true
    number-sections: true
    lightbox: true
    code-fold: true
    code-overflow: wrap
    code-tools: true

crossref:
  chapters: true

execute:
  freeze: auto
  tidy: true
  echo: false
  message: false
  warning: false


