project:
  type: book

lang: zh


book:
  title: "R语言学习笔记"
  author: "一把Fei刀"
  date: 2023/2/6
  chapters:
    - index.qmd
    - chapters/tidymodels.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
    favicon: images/favicon.png
    comments:
      hypothesis: true
    toc: true
    toc_float: true
    number-sections: true
    lightbox: true
    code-fold: true
    code-overflow: wrap
    code-tools: true
    execute:
      tidy: true
      echo: true
      message: false
      warning: false
  pdf:
    pdf-engine: xelatex
    documentclass: ctexbook
    toc: true
    toc-depth: 3
    colorlinks: true
    number-sections: true
    execute:
      tidy: true
      echo: false
      message: false
      warning: false

crossref:
  chapters: true

excute:
  freeze: auto



