```{r}
#| label: setup

library(tidyverse)
library(tidymodels)
tidymodels_prefer()
```

```{r}
#| label: data

rm(list = ls())
data("ames")

head(ames)
```

```{r}
#| label: 嵌套

ames |>
  mutate(Overall_Cond = fct_relevel(Overall_Cond, "Very_Poor")) |> # 将Overall_Cond变量的水平Very_Poor设置为基准水平
  nest(data = -MS_Zoning) -> nested_data
```

```{r}
#| label: 查看数据

nested_data

nested_data$data[[1]]
```

使用`nest()`后，data列中的每一行都是一个数据框，后续可以对每个数据框进行处理。

```{r}
#| label: 建模

# model ----
model <- multinom_reg() |>
  set_engine("nnet")

# formula ----
formula <- as.formula("Overall_Cond ~ Year_Built + Gr_Liv_Area")

# recipe(preprocess) ----
rcp <- recipe(formula = formula, data = ames) |>
  step_dummy(all_nominal(), -all_outcomes()) |>
  step_normalize(all_predictors())

workflow() |>
  add_model(model) |>
  add_recipe(rcp) -> wkflow

nested_data |>
  mutate(tidy = map(data, \(data) {
    wkflow |>
      fit(data) |>
      repair_call(data) |>
      tidy()
  }))
```

```{r}
#| label: 应用

nested_data |>
  mutate(tidy = map(data, \(data) {
    model |>
      fit(formula = formula,
          data = rcp |>
            prep() |>
            juice()) |>
      tidy(conf.int = TRUE)
  })) -> nested_data

nested_data |>
  mutate(tidy = map(tidy, ~filter(., term != "(Intercept)"))) |>
  select(-data) |>
  unnest(tidy) -> result
```
