
```{r}
#| label: setup
#| output: false

library(tidyverse)
library(mice)
library(tidymodels)
tidymodels_prefer()
```

## 模拟带缺失值的数据，包括两个自变量和一个因变量，并添加分组变量

```{r}
#| label: data

data <- data.frame(
  x1 = rnorm(100),
  x2 = rnorm(100),
  y = rnorm(100),
  group = sample(1:2, 100, replace = TRUE)
)

data$x1[sample(1:100, 20)] <- NA
data$x2[sample(1:100, 15)] <- NA

summary(data)
```

## 使用mice包生成插补数据集

```{r}
#| label: impute

data |>
  mice(m = 5, method = 'pmm', seed = 500) |> # <1>
  complete("long") |> # <2>
  nest(.by = c(group, .imp)) |> # <3>
  summarise(data = list(data), .by = group) -> data_nest # <4>
```
1. 生成5个插补数据集
2. 将数据集转换为长格式，结果是一个tibble，相比原始数据框添加了`.imp`列和`.id`列，分别表示插补数据集的编号和原始数据集的行号
3. 按照`group`和`.imp`分组生成嵌套数据集
4. 把5个插补数据集分别放入列表中，这种格式可以直接用于后面的`pool`函数（只是数据框的话不行）

# 使用tidymodels构建线性回归模型

```{r}
#| label: model

lm_spec <- linear_reg() |>
  set_engine("lm") |>
  set_mode("regression")

lm_fun <- \(data) {
  recipe(y ~ x1 + x2, data = data) |>
    step_normalize(x1) -> rec # 添加预处理步骤

  workflow() |>
    add_recipe(rec) |>
    add_model(lm_spec) |>
    fit(data)
}
```

## 拟合与合并

```{r}
#| label: fit

data_nest |>
  mutate(fit = map(data, \(x) map(x, lm_fun))) |> # <1>
  mutate(pool = map(fit, pool)) |> # <2>
  mutate(tidy = map(pool, \(x) tidy(x, conf.int = TRUE))) |> # <3>
  select(group, tidy) |>
  unnest(cols = tidy) -> result

result
```
1. 第一个`map`对每行应用函数，第二个`map`对该列表中的每个数据集应用函数
2. 对每组的列表可以直接用`pool`函数
3. `tidy`函数可以直接应用于`pool`结果
